language: ruby
jdk:
  - oraclejdk8
env:
  global:
    secure: GH_TOKEN
rvm:
  - 2.2
sudo: false
script:
  - chmod +x download-tensorics-projects-files.sh
  - ./download-tensorics-projects-files.sh
  - bundle exec jekyll build
  - bundle exec rake deploy

branches:
  only:
  - website-development
