title: "Tensorics"

description: "Tensorics Java Library Website"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tensorics.github.io/"

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
