title: "Tensorics"

description: "Tensorics Java Library Website"
baseurl: ""
url: "http://tensorics.github.io/"

tensorics-core-dir: "/projects/tensorics-core"
tensorics-core-javadoc: "/projects/tensorics-core/javadoc"
tensorics-expression-dir: "/projects/tensorics-expression"
tensorics-expression-javadoc: "/projects/tensorics-expression/javadoc"

exclude: ["Gemfile", "Rakefile", "*.iml", "*.sh", "README.adoc"]
encoding: utf-8
timezone: CET
asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
