---
layout: default
title: Home
---
:page-liquid:
= Tensorics - Handling multidimensional data with pleasure!
Tensorics is a java framework for data processing of multidimensional data.
The core object is called a Tensor which represents a collection of values of arbitrary
types, which are addressed by coordinates in an N-dimensional space (in some sense like a map with composite keys).
Whenever you are looking for one or more of the following features, tensorics might come in handy:

* multi-dimensional arrays.
* composite-key maps.
* mathematical operations over multidimensional data.

Despite the libraries core focus is on multidimensional data treatment and its name ("tensorics") is derived from "tensor" (a multidimensional object in mathematics), it provides several additional concepts which complement each other. The features are designed to work smoothly together, but each of them can of course also be used stand-alone. Te most important ones of them are:

```

* Tensors of arbitrary dimensionality as central object.
* Tensors can have elements of any (java) type.
* Structural and numerical operations on tensors.
* Java internal DSL (fluent API) for all operations on scalars and tensors.
* Quantities (value - unit pair).
* Full support for Tensors of quantities.
* Error and Validity propagation for quantities and tensors of quantities.
* Scripting of all functionality with deferred execution, which opens the
possibilities for parallel processing and massive distribution of calculations.
* Utilities for creating decision 'chains' in java, which emulate a concept similar to case-matching in scala.

== References
link:https://github.com/tensorics[Github Project]
link:{{ site.tensorics-core-javadoc }}[Tensorics Core Javadoc]
link:{{ site.tensorics-expression-javadoc }}[Tensorics Core Javadoc]
